version: '3'
services:
  postgres:
    image: "postgres:13.2"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=kashboard
    user: root
    network_mode: host
    ports:
      - "5432:5432"

  processing:
    image: "kashboard-processing:latest"
    depends_on:
      - kaspad
      - postgres
    command:
      - "/app/processing"
      - "--rpc-server=localhost:16610"
      - "--connection-string=postgres://root:pass@localhost:5432/kashboard?sslmode=disable"
    network_mode: host
    user: root

  grafana:
    image: "kashboard-grafana:latest"
    depends_on:
      - postgres
    environment:
      - GRAFANA_ADMIN_USERNAME=user
      - GRAFANA_ADMIN_PASSWORD=pass
      - POSTGRES_URL=localhost:5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=kashboard
    network_mode: host
    user: root
    ports:
      - "3000:3000"
