version: '3'
services:
  postgres:
    image: "postgres:13.2"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    user: root
    network_mode: host

  processing:
    image: "kasboard-processing:latest"
    depends_on:
      - postgres
    command:
      - "/app/processing"
      - "--testnet"
      - "--rpc-server=${KASPAD_ADDRESS}"
      - "--connection-string=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}?sslmode=disable"
    network_mode: host
    user: root
    restart: always

  grafana:
    image: "kasboard-grafana:latest"
    depends_on:
      - postgres
    environment:
      - GRAFANA_ADMIN_USERNAME=${GRAFANA_ADMIN_USERNAME}
      - GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GRAFANA_PORT=${GRAFANA_PORT}
      - POSTGRES_URL=localhost:5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    network_mode: host
    user: root
