version: '3'
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=kashboard
    user: root
    network_mode: host
    ports:
      - "5432:5432"

  grafana:
    image: "kashboard-grafana:latest"
    environment:
      - GRAFANA_ADMIN_USERNAME=user
      - GRAFANA_ADMIN_PASSWORD=pass
    network_mode: host
    user: root
    ports:
      - "3000:3000"

  kaspad:
    image: "kaspad:latest"
    command:
      - "/app/kaspad"
      - "--devnet"
    user: root
    network_mode: host
    ports:
      - "16610:16610"

  processing:
    image: "kashboard-processing:latest"
    depends_on:
      - kaspad
      - postgres
    command:
      - "/app/processing"
      - "--rpc-server=localhost:16610"
      - "--connection-string=postgres://root:pass@localhost:5432/kashboard?sslmode=disable"
    network_mode: host
    user: root

  web:
    image: "kashboard-web:latest"
    depends_on:
      - kaspad
      - postgres
    command:
      - "npx"
      - "next"
      - "start"
    environment:
      - PGUSER=root
      - PGPASSWORD=pass
      - PGDATABASE=kashboard
      - PGPORT=5432
    network_mode: host
    user: root
