{
 "title": "Kaspa",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "content": "# Network Health\n         " },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Header Amount",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  amount\nFROM header_amounts\nORDER BY \"timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Blue Score",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(blue_score)\nFROM blocks"
    }
   ]
  },
  {
   "title": "Block Amount",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  amount\nFROM block_amounts\nORDER BY \"timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Most Recent Pruning Point Movement",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(\"timestamp\" / 1000) AS \"time\" FROM pruning_point_movements ORDER BY \"timestamp\" DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  hashrate\nFROM blocks\nWHERE $__unixEpochFilter(\"timestamp\" / 1000)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Block Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  block_rate\nFROM analyzed_blocks\nWHERE $__unixEpochFilter(\"timestamp\" / 1000)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Parent Amount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  average_parent_amount\nFROM analyzed_blocks\nWHERE $__unixEpochFilter(\"timestamp\" / 1000)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  transaction_rate\nFROM analyzed_blocks\nWHERE $__unixEpochFilter(\"timestamp\" / 1000)\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": { "content": "# Debug\n         " },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Tip Amount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  amount\nFROM tip_amounts\nWHERE $__unixEpochFilter(\"timestamp\" / 1000)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Virtual Parent Amount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  amount\nFROM virtual_parent_amounts\nWHERE $__unixEpochFilter(\"timestamp\" / 1000)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blue Hashrate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  blue_hashrate\nFROM estimated_blue_hashrates\nWHERE $__unixEpochFilter(\"timestamp\" / 1000)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  difficulty\nFROM blocks\nWHERE $__unixEpochFilter(\"timestamp\" / 1000)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Block Inv Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  count\nFROM block_inv_counts\nWHERE $__unixEpochFilter(\"timestamp\" / 1000)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Transaction Inv Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  count\nFROM transaction_inv_counts\nWHERE $__unixEpochFilter(\"timestamp\" / 1000)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mempool Size (Transaction Amount)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  size\nFROM mempool_sizes\nWHERE $__unixEpochFilter(\"timestamp\" / 1000)\nORDER BY 1"
    }
   ]
  }
 ]
}