apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: localhost:5432
    database: kashboard
    user: root
    password: pass
    isDefault: true
    jsonData:
      sslmode: "disable" # disable/require/verify-ca/verify-full
      postgresVersion: 1302 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
