{
 "title": "Kaspa Testnet",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "content": "# Network Health\n         " },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Header Amount",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  amount\nFROM header_amounts\nORDER BY \"timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Block Amount",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  amount\nFROM block_amounts\nORDER BY \"timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Blue Score",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(blue_score)\nFROM blocks"
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  hashrate\nFROM blocks\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Block Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  block_rate\nFROM analyzed_blocks\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Parent Amount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  average_parent_amount\nFROM analyzed_blocks\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  transaction_rate\nFROM analyzed_blocks\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": { "content": "# Debug\n         " },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Tip Amount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  amount\nFROM tip_amounts\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Virtual Parent Amount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  amount\nFROM virtual_parent_amounts\nORDER BY 1"
    }
   ]
  }
 ]
}